global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'metrics-api'
    static_configs:
      - targets: ['metrics-api:8080']

  - job_name: 'test-metrics-app'
    static_configs:
      - targets: ['test-metrics-app:9102']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
