version: '3.8'

services:
  metrics-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metrics-api
    ports:
      - "8080:8080" # Maps host port 8080 to container port 8080
    environment:
      - SERVER_PORT=8080
      - PROMETHEUS_URL=http://prometheus:9090
      - PROMETHEUS_TIMEOUT=30
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - CACHE_ENABLED=true
      - CACHE_TTL=60
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - type: tmpfs
        target: /tmp
    user: "1000:1000"
    mem_limit: 512m
    cpus: 0.5
    labels:
      com.example.service: metrics-api
    networks:
      - metrics-network

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - metrics-network

volumes:
  prometheus-data:

networks:
  metrics-network:
    driver: bridge
