global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'metrics-api'
    static_configs:
      - targets: ['metrics-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s  # More frequent scraping for the API

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
